# Generated by Django 5.0.1 on 2024-03-01 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='Total')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('C', 'Created'), ('R', 'Reproved'), ('P', 'Pending'), ('E', 'Sent'), ('F', 'Finished')], default='C', max_length=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('product_id', models.PositiveIntegerField(verbose_name='Product ID')),
                ('product_variation', models.CharField(max_length=255, verbose_name='Product Variation')),
                ('product_variation_id', models.PositiveIntegerField(verbose_name='Product Variation ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('offer_price', models.FloatField(default=0, verbose_name='Offer Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product_image', models.CharField(max_length=2000, verbose_name='Product Image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
