# Generated by Django 5.0.1 on 2024-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('C', 'Created'), ('R', 'Reproved'), ('P', 'Pending'), ('S', 'Sent'), ('F', 'Finished')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
