# Generated by Django 5.0.1 on 2024-03-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='offer_price',
            field=models.FloatField(default=0, verbose_name='Preço de oferta'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(verbose_name='ID do Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(max_length=2000, verbose_name='Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.CharField(max_length=255, verbose_name='Variação do Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation_id',
            field=models.PositiveIntegerField(verbose_name='ID da Varição do Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
