# Generated by Django 5.0.1 on 2024-03-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('short_description', models.TextField(max_length=255, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/', verbose_name='Image')),
                ('slug', models.SlugField(unique=True)),
                ('price_marketing', models.FloatField(default=0, verbose_name='Price Marketing')),
                ('offer_price_marketing', models.FloatField(default=0, verbose_name='Offer Price Marketing')),
                ('product_type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1, verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variation Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('offer_price', models.FloatField(default=0, verbose_name='Offer Price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
            },
        ),
    ]
