# Generated by Django 5.0.1 on 2024-03-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Variação do Produto', 'verbose_name_plural': 'Variações do Produto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price_marketing',
            field=models.FloatField(default=0, verbose_name='Preço Oferta de Marketing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_marketing',
            field=models.FloatField(default=0, verbose_name='Preço de Marketing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='offer_price',
            field=models.FloatField(default=0, verbose_name='Preço de oferta'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Variação'),
        ),
    ]
