# Generated by Django 5.0.1 on 2024-02-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('short_description', models.TextField(max_length=255, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/', verbose_name='Product Image')),
                ('slug', models.SlugField(unique=True)),
                ('price_marketing', models.FloatField(default=0, verbose_name='Price Marketing')),
                ('price_marketing_offer', models.FloatField(default=0, verbose_name='Price Marketing Offer')),
                ('product_type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1, verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Product Site',
                'verbose_name_plural': 'Products Site',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('price_offer', models.FloatField(default=0, verbose_name='Price Offer')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsite', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Products Stock',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
