# Generated by Django 5.0.1 on 2024-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productvariation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price_marketing',
            field=models.FloatField(default=0, verbose_name='Preço de oferta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_marketing',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
