# Generated by Django 5.0.1 on 2024-03-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsite_productstock_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSite',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductStock',
            new_name='ProductVariation',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
    ]
