# Generated by Django 5.0.1 on 2024-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price_marketing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_marketing',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Nome'),
        ),
    ]
