# Generated by Django 5.0.1 on 2024-03-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_offer_price_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='offer_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço de oferta'),
        ),
    ]
