# Generated by Django 5.0.1 on 2024-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariation_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='offer_price',
            field=models.FloatField(default=0, verbose_name='Preço de oferta'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
