# Generated by Django 5.0.1 on 2024-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_alter_productvariation_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
    ]
