# Generated by Django 5.0.1 on 2024-03-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_offer',
            field=models.FloatField(default=0, verbose_name='Base Offer Price'),
        ),
    ]
