# Generated by Django 5.0.1 on 2024-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_price_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_offer',
            field=models.FloatField(default=0, verbose_name='Preço de oferta Base'),
        ),
    ]
