# Generated by Django 5.0.1 on 2024-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', upload_to='media/product_image/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
