# Generated by Django 5.0.1 on 2024-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productvariation_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome da Variação'),
        ),
    ]
